# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jz2eX4tDlRUrsE5DmX8oz55xMVzCddVD
"""

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
import pickle
import h5py

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/My\ Drive/Colab_Work
db = h5py.File("animals_features.hdf5", "r")
i = int(db["labels"].shape[0] * 0.75)

print("[INFO] tuning hyperparameters...")
params = {"C": [0.1, 1.0, 10.0, 100.0, 1000.0, 10000.0]}
model = GridSearchCV(LogisticRegression(), params, cv=3, n_jobs=-1)
model.fit(db["features"][:i], db["labels"][:i])
print("[INFO] the best hyperparametsrs: {}".format(model.best_params_))

print("[INFO] evaluating...")
preds = model.predict(db["features"][i:])
print(classification_report(db["labels"][i:], preds, target_names=db["label_names"]))

print("[INFO]  serializing model...")
f = open('animals.cpickle', "wb")
f.write(pickle.dumps(model.best_estimator_))
f.close()

db.close()