# -*- coding: utf-8 -*-
"""visualize_network.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ljwJBzaJoGhX4YlxbtZ1t0gO_YhPNoj1
"""

!apt-get install graphviz
!pip install graphviz
!pip install pydot-ng

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 1.x
import sys
sys.path.append('/content/drive/My Drive/Colab_Work/PPM/nn/conv')

from shallownet import ShallowNet
from keras.utils import plot_model

model = ShallowNet.build(width=32, height=32, depth=3, classes=10)
# %cd /content/drive/My\ Drive/Colab_Work
plot_model(model, to_file='shallownet.png', show_shapes=True)